// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Zxcvbn.EvaluatePassword(System.String,System.Collections.Generic.IEnumerable{System.String})~Zxcvbn.Result")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.DictionaryMatcher.MatchPassword(System.String)~System.Collections.Generic.IEnumerable{Zxcvbn.Match}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.DictionaryMatcher.#ctor(System.String,System.Collections.Generic.IEnumerable{System.String})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Zxcvbn.GetDictionaryMatchFeedback(Zxcvbn.Matcher.DictionaryMatch,System.Boolean,Zxcvbn.Result)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.DictionaryMatcher.MatchPassword(System.String,System.Collections.Generic.IDictionary{System.String,System.Collections.Generic.IDictionary{System.String,System.Int32}}@)~System.Collections.Generic.IEnumerable{Zxcvbn.Match}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.DictionaryMatcher.MatchDictionary(System.String,System.Collections.Generic.IDictionary{System.String,System.Collections.Generic.IDictionary{System.Int32,System.String}}@)~System.Collections.Generic.IEnumerable{Zxcvbn.Match}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.DictionaryMatcher.MatchDictionary(System.String,System.Collections.Generic.IDictionary{System.String,System.Collections.Generic.IDictionary{System.String,System.Int32}}@)~System.Collections.Generic.IEnumerable{Zxcvbn.Match}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.DictionaryMatcher.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String}@)~System.Collections.Generic.Dictionary{System.String,System.Int32}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.DictionaryMatcher.MatchPassword(System.String)~System.Collections.Generic.IEnumerable{Zxcvbn.Matcher.DictionaryMatch}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.DictionaryMatcher.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String})~System.Collections.Generic.Dictionary{System.String,System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.DefaultMatcherFactory.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String})~System.Collections.Generic.Dictionary{System.String,System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.PasswordScoring.CalculateUppercaseEntropy(System.String)~System.Double")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.DefaultMatcherFactory.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String}@)~System.Collections.Generic.Dictionary{System.String,System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.DefaultMatcherFactory.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String}@)~System.Collections.Generic.IEnumerable{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.DefaultMatcherFactory.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String}@)~System.Collections.Generic.IEnumerable{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.DefaultMatcherFactory.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String}@)~System.Collections.Generic.IEnumerable{System.}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.DefaultMatcherFactory.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String}@)~System.Collections.Generic.IEnumerable{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:文字列を大文字に標準化します", Justification = "<保留中>", Scope = "member", Target = "~M:Zxcvbn.Matcher.Matching.BuildRankedDictionary(System.Collections.Generic.IEnumerable{System.String}@)~System.Collections.Generic.Dictionary{System.String,System.Int32}")]