//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zxcvbn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zxcvbn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   you
        ///i
        ///the
        ///to
        ///a
        ///&apos;s
        ///it
        ///and
        ///that
        ///&apos;t
        ///of
        ///is
        ///in
        ///what
        ///we
        ///me
        ///this
        ///he
        ///for
        ///my
        ///on
        ///have
        ///your
        ///do
        ///was
        ///&apos;m
        ///no
        ///not
        ///be
        ///are
        ///don
        ///&apos;re
        ///know
        ///can
        ///with
        ///but
        ///all
        ///so
        ///just
        ///there
        ///here
        ///they
        ///like
        ///&apos;ll
        ///get
        ///she
        ///go
        ///if
        ///right
        ///out
        ///about
        ///up
        ///at
        ///him
        ///now
        ///oh
        ///one
        ///come
        ///well
        ///her
        ///how
        ///yeah
        ///&apos;ve
        ///will
        ///got
        ///want
        ///think
        ///as
        ///see
        ///did
        ///good
        ///who
        ///why
        ///from
        ///let
        ///his
        ///yes
        ///when
        ///going
        ///time
        ///an
        ///okay
        ///back
        ///look
        ///us
        ///would
        ///them
        ///where
        ///were
        ///take
        ///then
        ///had
        ///or
        ///been
        ///our
        ///gonna
        ///tell
        ///really
        ///man        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mary
        ///patricia
        ///linda
        ///barbara
        ///elizabeth
        ///jennifer
        ///maria
        ///susan
        ///margaret
        ///dorothy
        ///lisa
        ///nancy
        ///karen
        ///betty
        ///helen
        ///sandra
        ///donna
        ///carol
        ///ruth
        ///sharon
        ///michelle
        ///laura
        ///sarah
        ///kimberly
        ///deborah
        ///jessica
        ///shirley
        ///cynthia
        ///angela
        ///melissa
        ///brenda
        ///amy
        ///anna
        ///rebecca
        ///virginia
        ///kathleen
        ///pamela
        ///martha
        ///debra
        ///amanda
        ///stephanie
        ///carolyn
        ///christine
        ///marie
        ///janet
        ///catherine
        ///frances
        ///ann
        ///joyce
        ///diane
        ///alice
        ///julie
        ///heather
        ///teresa
        ///doris
        ///gloria
        ///evelyn
        ///jean
        ///cheryl
        ///mildred
        ///katherine
        ///joan
        ///ashley
        ///judi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   james
        ///john
        ///robert
        ///michael
        ///william
        ///david
        ///richard
        ///charles
        ///joseph
        ///thomas
        ///christopher
        ///daniel
        ///paul
        ///mark
        ///donald
        ///george
        ///kenneth
        ///steven
        ///edward
        ///brian
        ///ronald
        ///anthony
        ///kevin
        ///jason
        ///matthew
        ///gary
        ///timothy
        ///jose
        ///larry
        ///jeffrey
        ///frank
        ///scott
        ///eric
        ///stephen
        ///andrew
        ///raymond
        ///gregory
        ///joshua
        ///jerry
        ///dennis
        ///walter
        ///patrick
        ///peter
        ///harold
        ///douglas
        ///henry
        ///carl
        ///arthur
        ///ryan
        ///roger
        ///joe
        ///juan
        ///jack
        ///albert
        ///jonathan
        ///justin
        ///terry
        ///gerald
        ///keith
        ///samuel
        ///willie
        ///ralph
        ///lawrence
        ///nicholas
        ///roy
        ///benjamin [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   123456
        ///123456789
        ///qwerty
        ///password
        ///111111
        ///12345678
        ///abc123
        ///1234567
        ///password1
        ///12345
        ///1234567890
        ///123123
        ///000000
        ///iloveyou
        ///1234
        ///1q2w3e4r5t
        ///qwertyuiop
        ///123
        ///monkey
        ///dragon
        ///123456a
        ///654321
        ///123321
        ///666666
        ///1qaz2wsx
        ///myspace1
        ///121212
        ///homelesspa
        ///123qwe
        ///a123456
        ///123abc
        ///1q2w3e4r
        ///qwe123
        ///7777777
        ///qwerty123
        ///target123
        ///tinkle
        ///987654321
        ///qwerty1
        ///222222
        ///zxcvbnm
        ///1g2w3e4r
        ///gwerty
        ///zag12wsx
        ///gwerty123
        ///555555
        ///fuckyou
        ///112233
        ///asdfghjkl
        ///1q2w3e
        ///123123123
        ///qazwsx
        ///computer
        ///princess
        ///12345a
        ///ashley
        ///159 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Passwords {
            get {
                return ResourceManager.GetString("Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   smith
        ///johnson
        ///williams
        ///jones
        ///brown
        ///davis
        ///miller
        ///wilson
        ///moore
        ///taylor
        ///anderson
        ///thomas
        ///jackson
        ///white
        ///harris
        ///martin
        ///thompson
        ///garcia
        ///martinez
        ///robinson
        ///clark
        ///rodriguez
        ///lewis
        ///lee
        ///walker
        ///hall
        ///allen
        ///young
        ///hernandez
        ///king
        ///wright
        ///lopez
        ///hill
        ///scott
        ///green
        ///adams
        ///baker
        ///gonzalez
        ///nelson
        ///carter
        ///mitchell
        ///perez
        ///roberts
        ///turner
        ///phillips
        ///campbell
        ///parker
        ///evans
        ///edwards
        ///collins
        ///stewart
        ///sanchez
        ///morris
        ///rogers
        ///reed
        ///cook
        ///morgan
        ///bell
        ///murphy
        ///bailey
        ///rivera
        ///cooper
        ///richardson
        ///cox
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
    }
}
